services: 
  stend-web:
    build:
      context: .
    image: stend-web
    environment:
      # Affichage de la taille maximale pour un seul fichier sur la page d'accueil du site
      FILE_MAX_SIZE: 5 GB
      # URL de l'API, les adresses IP locales (localhost, 127.0.0.1 etc...) ne corresponderaient pas forcément à votre configuration
      API_BASE_URL: http://localhost:3000
      # Port sur lequel le serveur web écoutera
      PORT: 80
      # Afficher ".html" dans le chemin des fichiers ?
      # Exemple - true : https://stend.example.com/d.html?frezazer - Il est préférable d'utiliser cette option
      # Exemple - false : https://stend.example.com/d?frezazer
      # Sur certains hébergeurs comme Vercel, vous pouvez utiliser la propriété "cleanUrls" du vercel.json, puis définir la variable sur false
      SHOW_HTML_EXTENSION: false
    ports:
      - 80:80
    volumes:
      - stend_web:/usr/src/app/build

volumes:
  stend_web:

